---
title: "Meta-analysis"
author: "Yuchan Mou"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
options(knitr.table.format = "html")
```

```{r load packages, include=FALSE, echo=FALSE, message=FALSE, warning=FALSE}
# load pkgs
packages <- c("tidyverse", "openxlsx", "meta", "readxl", "RColorBrewer")
sapply(packages, library, character.only = T)
```

```{r, eval=FALSE}
ap <- c(
  "hs_no2_yr_hs_t",
  "hs_pm25_yr_hs_t",
  "hs_pm25abs_yr_hs_t",
  "hs_pm10_yr_hs_t"
)

out <- c("AL_2_tot", "AL_2_tot_wavg", "AL_z2_tot", "AL_z2_tot_wavg")
```

```{r import data, eval=FALSE}
analysis_date <- Sys.Date()
sab <- read_excel("/Users/ymou/helix_project/results/airpollution_total_mainoutcome_sab2023-09-19.xlsx")
ede <- read_excel("/Users/ymou/helix_project/results/airpollution_total_mainoutcome_ede2023-09-19.xlsx")
bib <- read_excel("/Users/ymou/helix_project/results/airpollution_total_mainoutcome_bib2023-09-19.xlsx")
rhea <- read_excel("/Users/ymou/helix_project/results/airpollution_total_mainoutcome_rhea2023-09-19.xlsx")
kanc <- read_excel("/Users/ymou/helix_project/results/airpollution_total_mainoutcome_kanc2023-09-19.xlsx")
moba <- read_excel("/Users/ymou/helix_project/results/airpollution_total_mainoutcome_moba2023-09-19.xlsx")
```

```{r select var for meta, eval=FALSE}
# Only selected model 4
sab <- sab %>%
  mutate(cohort = "sab") %>%
  select(cohort, Outcome, Predictor, beta_mod4, std_mod4)
ede <- ede %>%
  mutate(cohort = "ede") %>%
  select(cohort, Outcome, Predictor, beta_mod4, std_mod4)
bib <- bib %>%
  mutate(cohort = "bib") %>%
  select(cohort, Outcome, Predictor, beta_mod4, std_mod4)
rhea <- rhea %>%
  mutate(cohort = "rhea") %>%
  select(cohort, Outcome, Predictor, beta_mod4, std_mod4)
kanc <- kanc %>%
  mutate(cohort = "kanc") %>%
  select(cohort, Outcome, Predictor, beta_mod4, std_mod4)
moba <- moba %>%
  mutate(cohort = "moba") %>%
  select(cohort, Outcome, Predictor, beta_mod4, std_mod4)

df <- rbind(sab, ede, bib, rhea, kanc, moba)
```

```{r calc combined effect and se, eval=FALSE}
meta_tbl <- as.data.frame(matrix(NA, nrow = 1, ncol = 4))
colnames(meta_tbl) <- c(
  "Outcome", "Predictor",
  "c_std.error", "c_beta"
)

count <- 0
for (o in out) {
  for (d in ap) {
    sep_coefs <- df %>%
      filter(Outcome == o) %>%
      filter(Predictor == d)

    sep_coefs <- sep_coefs %>%
      mutate(
        w = 1 / (std_mod4)^2
      )

    count <- count + 1
    if (d %in% c("hs_no2_yr_hs_t", "hs_pm25_yr_hs_t")) {
      meta_tbl[count, 1] <- o
      meta_tbl[count, 2] <- d
      meta_tbl[count, 3] <- sqrt(1 / (sum(sep_coefs$w)))
      meta_tbl[count, 4] <- (sep_coefs$w[1] * sep_coefs$beta_mod4[1] +
        sep_coefs$w[2] * sep_coefs$beta_mod4[2] +
        sep_coefs$w[3] * sep_coefs$beta_mod4[3] +
        sep_coefs$w[4] * sep_coefs$beta_mod4[4] +
        sep_coefs$w[5] * sep_coefs$beta_mod4[5] +
        sep_coefs$w[6] * sep_coefs$beta_mod4[6]) / (sum(sep_coefs$w))
    }
    if (d %in% c("hs_pm10_yr_hs_t")) {
      meta_tbl[count, 1] <- o
      meta_tbl[count, 2] <- d
      meta_tbl[count, 3] <- sqrt(1 / (sum(sep_coefs$w)))
      meta_tbl[count, 4] <- (sep_coefs$w[1] * sep_coefs$beta_mod4[1] +
        sep_coefs$w[2] * sep_coefs$beta_mod4[2] +
        sep_coefs$w[3] * sep_coefs$beta_mod4[3] +
        sep_coefs$w[4] * sep_coefs$beta_mod4[4] +
        sep_coefs$w[5] * sep_coefs$beta_mod4[5]) / (sum(sep_coefs$w))
    }
    if (d %in% c("hs_pm25abs_yr_hs_t")) {
      meta_tbl[count, 1] <- o
      meta_tbl[count, 2] <- d
      meta_tbl[count, 3] <- sqrt(1 / (sum(sep_coefs$w)))
      meta_tbl[count, 4] <- (sep_coefs$w[1] * sep_coefs$beta_mod4[1] +
        sep_coefs$w[2] * sep_coefs$beta_mod4[2] +
        sep_coefs$w[3] * sep_coefs$beta_mod4[3] +
        sep_coefs$w[4] * sep_coefs$beta_mod4[4]) / (sum(sep_coefs$w))
    }
  }
}

meta_tbl <- meta_tbl %>%
  mutate(
    cohort = "total"
  ) %>%
  relocate(cohort, .before = "Outcome") %>%
  relocate(c_beta, .before = "c_std.error")
```

```{r merge to meta table, eval=FALSE}
df <- df %>%
  dplyr::rename(
    "beta" = "beta_mod4",
    "se" = "std_mod4"
  )

meta_tbl <- meta_tbl %>%
  dplyr::rename(
    "beta" = "c_beta",
    "se" = "c_std.error"
  )

df_meta <- rbind(df, meta_tbl)
df_meta <- df_meta %>%
  arrange(Outcome, Predictor)

write.xlsx(df_meta, file = paste("/Users/ymou/helix_project/results/", "meta_tbl", ".xlsx", sep = ""), rowNames = FALSE, colNames = TRUE)
# I manually added n
```

```{r calc ci}
df_meta <- read_excel("/Users/ymou/helix_project/results/meta_tbl2023-09-19.xlsx")
df_meta <- df_meta %>%
  mutate(
    w = 1 / (se)^2,
    hi = beta + 1.96 * se / sqrt(n),
    low = beta - 1.96 * se / sqrt(n)
  ) %>%
  mutate_at("Predictor", as_factor) %>%
  mutate(Predictor = recode(Predictor,
    "hs_no2_yr_hs_t" = "NO[2]",
    "hs_pm10_yr_hs_t" = "PM[10]",
    "hs_pm25_yr_hs_t" = "PM[2.5]",
    "hs_pm25abs_yr_hs_t" = "PM[2.5][abs]"
  )) %>%
  mutate(Cohort = fct_relevel(
    cohort,
    "total", "sab", "ede", "bib",
    "rhea", "kanc", "moba"
  )) %>%
  mutate(Cohort = recode(Cohort,
    "total" = "Summary effect size",
    "sab" = "SAB",
    "ede" = "EDEN",
    "bib" = "BIB",
    "rhea" = "RHEA",
    "kanc" = "KANC",
    "moba" = "MOBA"
  ))
```

## Forest plot

```{r forest plot, fig.asp = 0.8, fig.width=9}
library("ggsci")

df_meta_AL2 <- df_meta %>%
  filter(Outcome %in% c("AL_2_tot"))

p <- ggplot(
  data = df_meta_AL2,
  aes(x = Cohort, y = beta, ymin = low, ymax = hi)
) +
  geom_pointrange(aes(col = Cohort)) +
  geom_hline(aes(fill = Cohort), yintercept = 0, linetype = 2) +
  xlab("") +
  ylab("Effect sizes (95% Confidence Interval)") +
  geom_errorbar(aes(ymin = low, ymax = hi, col = Cohort), width = 0.5, cex = 1) +
  scale_color_npg() +
  guides(color = guide_legend(reverse=TRUE)) + 
  facet_wrap(~Predictor, strip.position = "left", nrow = 9, scales = "free_y", labeller = labeller(Predictor = label_parsed)) +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.x = element_text(face = "bold"),
    axis.title = element_text(size = 12, face = "bold"),
    strip.text.y.left = element_text(angle = 0, face = "bold")
  ) +
  coord_flip() +
  ggtitle("Cut-off based AL score")


p

df_meta_AL2 <- df_meta %>%
  filter(Outcome %in% c("AL_2_tot_wavg"))

p <- ggplot(
  data = df_meta_AL2,
  aes(x = Cohort, y = beta, ymin = low, ymax = hi)
) +
  geom_pointrange(aes(col = Cohort)) +
  xlab("") +
  geom_hline(aes(fill = Cohort), yintercept = 0, linetype = 2) +
  ylab("Effect sizes (95% Confidence Interval)") +
  geom_errorbar(aes(ymin = low, ymax = hi, col = Cohort), width = 0.5, cex = 1) +
  scale_color_npg() +
  guides(color = guide_legend(reverse=TRUE)) + 
  facet_wrap(~Predictor, strip.position = "left", nrow = 9, scales = "free_y", labeller = labeller(Predictor = label_parsed)) +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.x = element_text(face = "bold"),
    axis.title = element_text(size = 12, face = "bold"),
    strip.text.y.left = element_text(angle = 0, face = "bold")
  ) +
  coord_flip() +
  ggtitle("Cut-off based weighted average AL score")

p


df_meta_AL2 <- df_meta %>%
  filter(Outcome %in% c("AL_z2_tot"))

p <- ggplot(
  data = df_meta_AL2,
  aes(x = Cohort, y = beta, ymin = low, ymax = hi)
) +
  geom_pointrange(aes(col = Cohort)) +
  geom_hline(aes(fill = Cohort), yintercept = 0, linetype = 2) +
  xlab("") +
  ylab("Effect sizes (95% Confidence Interval)") +
  geom_errorbar(aes(ymin = low, ymax = hi, col = Cohort), width = 0.5, cex = 1) +
  scale_color_npg() +
  guides(color = guide_legend(reverse=TRUE)) + 
  facet_wrap(~Predictor, strip.position = "left", nrow = 9, scales = "free_y", labeller = labeller(Predictor = label_parsed)) +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.x = element_text(face = "bold"),
    axis.title = element_text(size = 12, face = "bold"),
    strip.text.y.left = element_text(angle = 0, face = "bold")
  ) +
  coord_flip() +
  ggtitle("Z-score based AL score")

p

df_meta_AL2 <- df_meta %>%
  filter(Outcome %in% c("AL_z2_tot_wavg"))

p <- ggplot(
  data = df_meta_AL2,
  aes(x = Cohort, y = beta, ymin = low, ymax = hi)
) +
  geom_pointrange(aes(col = Cohort)) +
  geom_hline(aes(fill = Cohort), yintercept = 0, linetype = 2) +
  xlab("") +
  ylab("Effect sizes (95% Confidence Interval)") +
  geom_errorbar(aes(ymin = low, ymax = hi, col = Cohort), width = 0.5, cex = 1) +
  scale_color_npg() +
  guides(color = guide_legend(reverse=TRUE)) + 
  facet_wrap(~Predictor, strip.position = "left", nrow = 9, scales = "free_y", labeller = labeller(Predictor = label_parsed)) +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.x = element_text(face = "bold"),
    axis.title = element_text(size = 12, face = "bold"),
    strip.text.y.left = element_text(angle = 0, face = "bold")
  ) +
  coord_flip() +
  ggtitle("Z-score based weighted average AL score")

p
```

```{r, eval=FALSE}
library(grid)
library(forestploter)

df_meta_AL2 <- df_meta %>%
  filter(Outcome %in% c("AL_2_tot")) %>%
  filter(Predictor %in% c("hs_no2_yr_hs_t"))

p <-
  df_meta_AL2 |>
  ggplot(aes(y = fct_rev(cohort))) +
  theme_classic() +
  geom_point(aes(x = beta), shape = 15, size = 3) +
  geom_linerange(aes(xmin = low, xmax = hi)) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  labs(x = "Beta coefficient", y = "") +
  ggtitle("AL_2_tot no2")
p

df_meta_AL2 <- df_meta %>%
  filter(Outcome %in% c("AL_2_tot")) %>%
  filter(Predictor %in% c("hs_pm10_yr_hs_t"))

p <-
  df_meta_AL2 |>
  ggplot(aes(y = fct_rev(cohort))) +
  theme_classic() +
  geom_point(aes(x = beta), shape = 15, size = 3) +
  geom_linerange(aes(xmin = low, xmax = hi)) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  labs(x = "Beta coefficient", y = "") +
  ggtitle("AL_2_tot pm10")
p


df_meta_AL2 <- df_meta %>%
  filter(Outcome %in% c("AL_2_tot")) %>%
  filter(Predictor %in% c("hs_pm25_yr_hs_t"))

p <-
  df_meta_AL2 |>
  ggplot(aes(y = fct_rev(cohort))) +
  theme_classic() +
  geom_point(aes(x = beta), shape = 15, size = 3) +
  geom_linerange(aes(xmin = low, xmax = hi)) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  labs(x = "Beta coefficient", y = "") +
  ggtitle("AL_2_tot pm25")
p

df_meta_AL2 <- df_meta %>%
  filter(Outcome %in% c("AL_2_tot")) %>%
  filter(Predictor %in% c("hs_pm25abs_yr_hs_t"))

p <-
  df_meta_AL2 |>
  ggplot(aes(y = fct_rev(cohort))) +
  theme_classic() +
  geom_point(aes(x = beta), shape = 15, size = 3) +
  geom_linerange(aes(xmin = low, xmax = hi)) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  labs(x = "Beta coefficient", y = "") +
  ggtitle("AL_2_tot pm25abs")
p
```

```{r, eval=FALSE}
# This is not a correct method

analysis <- "ap_mainoutcome_mod4_meta"

mod_tbl <- as.data.frame(matrix(NA, nrow = 1, ncol = 14))
colnames(mod_tbl) <- c(
  "Outcome", "Predictor",
  "TE.random", "pval.random", "lower.random", "upper.random",
  "tau2", "lower.tau2", "upper.tau2",
  "I2", "lower.I2", "upper.I2",
  "Q", "pval.Q"
)

count <- 0

for (o in out) {
  for (d in ap) {
    sep_coefs <- df %>%
      filter(Outcome == o) %>%
      filter(Predictor == d)

    m.gen <- metagen(
      TE = beta_mod4,
      seTE = std_mod4,
      studlab = cohort,
      data = sep_coefs,
      sm = "SMD",
      fixed = FALSE,
      random = TRUE,
      method.tau = "REML",
      hakn = TRUE,
      title = paste(o, d, sep = "_")
    )

    count <- count + 1
    mod_tbl[count, 1] <- o
    mod_tbl[count, 2] <- d
    mod_tbl[count, 3] <- m.gen$TE.random
    mod_tbl[count, 4] <- m.gen$pval.random
    mod_tbl[count, 5] <- m.gen$lower.random
    mod_tbl[count, 6] <- m.gen$upper.random
    mod_tbl[count, 7] <- m.gen$tau2
    mod_tbl[count, 8] <- m.gen$lower.tau2
    mod_tbl[count, 9] <- m.gen$upper.tau2
    mod_tbl[count, 10] <- m.gen$I2
    mod_tbl[count, 11] <- m.gen$lower.I2
    mod_tbl[count, 12] <- m.gen$upper.I2
    mod_tbl[count, 13] <- m.gen$Q
    mod_tbl[count, 14] <- m.gen$pval.Q
  }
}

write.xlsx(mod_tbl, file = paste("/Users/ymou/helix_project/results/", analysis, analysis_date, ".xlsx", sep = ""), rowNames = FALSE, colNames = TRUE)
```
