---
title: "Plots"
author: "Yuchan Mou"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
options(knitr.table.format = "html")
```

```{r load packages, include=FALSE, echo=FALSE, message=FALSE, warning=FALSE}
# load pkgs
packages <- c("tidyverse", "openxlsx", "meta", "readxl", "RColorBrewer", "ggsci")
sapply(packages, library, character.only = T)
```

```{r import data, eval=T}
analysis_date <- Sys.Date()

ap_tot_out <- read_excel("/Users/ymou/helix_project/results/airpollution_total_mainoutcome2023-09-20.xlsx")
ap_tot_outps <- read_excel("/Users/ymou/helix_project/results/airpollution_total_outcomepsystem2023-09-20.xlsx")
ap_tot_outzps <- read_excel("/Users/ymou/helix_project/results/airpollution_total_outcomepsystem_zscore2023-09-20.xlsx")

ap_hsr_out <- read_excel("/Users/ymou/helix_project/results/airpollution_hsrp_mainoutcome2023-09-20.xlsx") %>% filter(!str_detect(Predictor, "_p$")) # other places not incl
ap_hsr_outps <- read_excel("/Users/ymou/helix_project/results/airpollution_hsrp_outcomepsystem2023-09-20.xlsx") %>% filter(!str_detect(Predictor, "_p$")) # other places not incl
ap_hsr_outzps <- read_excel("/Users/ymou/helix_project/results/airpollution_hsrp_outcomepsystem_zscore2023-09-20.xlsx") %>% filter(!str_detect(Predictor, "_p$")) # other places not incl
```


# Forest plot

## Air pollutants and main outcomes
```{r}
ap_tot_out <- ap_tot_out %>%
  dplyr::rename(
    "beta" = "beta_mod4",
    "low" = "cilo_mod4",
    "hi" = "cihi_mod4"
  ) %>% 
  mutate_at("Predictor", as_factor) %>%
  mutate(Predictor = recode(Predictor,
    "hs_no2_yr_hs_t" = "NO[2]",
    "hs_pm10_yr_hs_t" = "PM[10]",
    "hs_pm25_yr_hs_t" = "PM[2.5]",
    "hs_pm25abs_yr_hs_t" = "PM[2.5][abs]"
  )) 
```

```{r fig.asp = 0.8, fig.width=10}
p <- ggplot(
  data = ap_tot_out,
  aes(x = Outcome, y = beta, ymin = low, ymax = hi)
) +
  geom_pointrange(aes(col = Outcome)) +
  geom_hline(aes(fill = Outcome), yintercept = 0, linetype = 2) +
  xlab("") +
  ylab("Effect sizes (95% Confidence Interval)") +
  geom_errorbar(aes(ymin = low, ymax = hi, col = Outcome), width = 0.5, cex = 1) +
  scale_color_npg() +
  guides(color = guide_legend(reverse=TRUE)) +
  facet_wrap(~Predictor, strip.position = "left", nrow = 9, scales = "free_y", labeller = labeller(Predictor = label_parsed)) +
  guides(color = guide_legend(reverse=TRUE)) + 
  #scale_y_continuous(limits = c(-1, 6), breaks = c(-1, 0, 1, 2, 3, 4, 5, 6)) +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.x = element_text(face = "bold"),
    axis.title = element_text(size = 12, face = "bold"),
    strip.text.y.left = element_text(angle = 0, face = "bold")
  ) +
  coord_flip() +
  ggtitle("")

p
```


## Air pollutants and outcomes per physiological systems
### Cut-off based AL score
```{r}
ap_tot_outps <- ap_tot_outps %>%
  dplyr::rename(
    "beta" = "beta_mod4",
    "low" = "cilo_mod4",
    "hi" = "cihi_mod4"
  ) %>% 
  mutate_at("Predictor", as_factor) %>%
  mutate(Predictor = recode(Predictor,
    "hs_no2_yr_hs_t" = "NO[2]",
    "hs_pm10_yr_hs_t" = "PM[10]",
    "hs_pm25_yr_hs_t" = "PM[2.5]",
    "hs_pm25abs_yr_hs_t" = "PM[2.5][abs]"
  )) 
```

```{r fig.asp = 0.8, fig.width=10}
p <- ggplot(
  data = ap_tot_outps,
  aes(x = Outcome, y = beta, ymin = low, ymax = hi)
) +
  geom_pointrange(aes(col = Outcome)) +
  geom_hline(aes(fill = Outcome), yintercept = 0, linetype = 2) +
  xlab("") +
  ylab("Effect sizes (95% Confidence Interval)") +
  geom_errorbar(aes(ymin = low, ymax = hi, col = Outcome), width = 0.5, cex = 1) +
  scale_color_npg() +
  guides(color = guide_legend(reverse=TRUE)) + 
  facet_wrap(~Predictor, strip.position = "left", nrow = 9, scales = "free_y", labeller = labeller(Predictor = label_parsed)) +
  guides(color = guide_legend(reverse=TRUE)) + 
  #scale_y_continuous(limits = c(-1, 6), breaks = c(-1, 0, 1, 2, 3, 4, 5, 6)) +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.x = element_text(face = "bold"),
    axis.title = element_text(size = 12, face = "bold"),
    strip.text.y.left = element_text(angle = 0, face = "bold")
  ) +
  coord_flip() +
  ggtitle("")

p
```

### Z-score based AL score
```{r}
ap_tot_outzps <- ap_tot_outzps %>%
  dplyr::rename(
    "beta" = "beta_mod4",
    "low" = "cilo_mod4",
    "hi" = "cihi_mod4"
  ) %>% 
  mutate_at("Predictor", as_factor) %>%
  mutate(Predictor = recode(Predictor,
    "hs_no2_yr_hs_t" = "NO[2]",
    "hs_pm10_yr_hs_t" = "PM[10]",
    "hs_pm25_yr_hs_t" = "PM[2.5]",
    "hs_pm25abs_yr_hs_t" = "PM[2.5][abs]"
  )) 
```

```{r fig.asp = 0.8, fig.width=10}
p <- ggplot(
  data = ap_tot_outzps,
  aes(x = Outcome, y = beta, ymin = low, ymax = hi)
) +
  geom_pointrange(aes(col = Outcome)) +
  geom_hline(aes(fill = Outcome), yintercept = 0, linetype = 2) +
  xlab("") +
  ylab("Effect sizes (95% Confidence Interval)") +
  geom_errorbar(aes(ymin = low, ymax = hi, col = Outcome), width = 0.5, cex = 1) +
  scale_color_npg() +
  guides(color = guide_legend(reverse=TRUE)) + 
  facet_wrap(~Predictor, strip.position = "left", nrow = 9, scales = "free_y", labeller = labeller(Predictor = label_parsed)) +
  guides(color = guide_legend(reverse=TRUE)) + 
  #scale_y_continuous(limits = c(-1, 6), breaks = c(-1, 0, 1, 2, 3, 4, 5, 6)) +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.x = element_text(face = "bold"),
    axis.title = element_text(size = 12, face = "bold"),
    strip.text.y.left = element_text(angle = 0, face = "bold")
  ) +
  coord_flip() +
  ggtitle("")

p
```


## Air pollutants(home, school, commuting) and main outcomes
```{r}
ap_hsr_out <- ap_hsr_out %>%
  dplyr::rename(
    "beta" = "beta_mod4",
    "low" = "cilo_mod4",
    "hi" = "cihi_mod4"
  ) %>% 
  mutate(type = if_else(str_detect(Predictor, "_h$"), "Home", 
                        if_else(str_detect(Predictor, "_s$"), "School", "Commuting"))) %>% 
  mutate_at("Predictor", as_factor) %>%
  mutate(Predictor = recode(Predictor,
    "hs_no2_yr_hs_h" = "NO[2]",
    "hs_no2_yr_hs_s" = "NO[2]",
    "hs_no2_yr_hs_r" = "NO[2]",
    "hs_pm10_yr_hs_h" = "PM[10]",
    "hs_pm10_yr_hs_s" = "PM[10]",
    "hs_pm10_yr_hs_r" = "PM[10]",
    "hs_pm25_yr_hs_h" = "PM[2.5]",
    "hs_pm25_yr_hs_s" = "PM[2.5]",
    "hs_pm25_yr_hs_r" = "PM[2.5]",
    "hs_pm25abs_yr_hs_h" = "PM[2.5][abs]",
    "hs_pm25abs_yr_hs_s" = "PM[2.5][abs]",
    "hs_pm25abs_yr_hs_r" = "PM[2.5][abs]"
  )) 
```

```{r fig.asp = 0.8, fig.width=10}
p <- ggplot(
  data = ap_hsr_out,
  aes(x = Outcome, y = beta, ymin = low, ymax = hi)
) +
  geom_pointrange(aes(col = Outcome)) +
  geom_hline(aes(fill = Outcome), yintercept = 0, linetype = 2) +
  xlab("") +
  ylab("Effect sizes (95% Confidence Interval)") +
  geom_errorbar(aes(ymin = low, ymax = hi, col = Outcome), width = 0.5, cex = 1) +
  scale_color_npg() +
  guides(color = guide_legend(reverse=TRUE)) + 
  facet_grid(Predictor~type, labeller = labeller(Predictor = label_parsed)) +
  #scale_y_continuous(limits = c(-1, 6), breaks = c(-1, 0, 1, 2, 3, 4, 5, 6)) +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.x = element_text(face = "bold"),
    axis.title = element_text(size = 12, face = "bold"),
    strip.text.y = element_text(angle = 0, face = "bold")
  ) +
  coord_flip() +
  ggtitle("")

p
```


## Air pollutants(home, school, commuting) and outcomes per physiological systems
### Cut-off based AL score
```{r}
ap_hsr_outps <- ap_hsr_outps %>%
  dplyr::rename(
    "beta" = "beta_mod4",
    "low" = "cilo_mod4",
    "hi" = "cihi_mod4"
  ) %>% 
  mutate(type = if_else(str_detect(Predictor, "_h$"), "Home", 
                        if_else(str_detect(Predictor, "_s$"), "School", "Commuting"))) %>% 
  mutate_at("Predictor", as_factor) %>%
  mutate(Predictor = recode(Predictor,
    "hs_no2_yr_hs_h" = "NO[2]",
    "hs_no2_yr_hs_s" = "NO[2]",
    "hs_no2_yr_hs_r" = "NO[2]",
    "hs_pm10_yr_hs_h" = "PM[10]",
    "hs_pm10_yr_hs_s" = "PM[10]",
    "hs_pm10_yr_hs_r" = "PM[10]",
    "hs_pm25_yr_hs_h" = "PM[2.5]",
    "hs_pm25_yr_hs_s" = "PM[2.5]",
    "hs_pm25_yr_hs_r" = "PM[2.5]",
    "hs_pm25abs_yr_hs_h" = "PM[2.5][abs]",
    "hs_pm25abs_yr_hs_s" = "PM[2.5][abs]",
    "hs_pm25abs_yr_hs_r" = "PM[2.5][abs]"
  )) 
```

```{r fig.asp = 1, fig.width=10}
p <- ggplot(
  data = ap_hsr_outps,
  aes(x = Outcome, y = beta, ymin = low, ymax = hi)
) +
  geom_pointrange(aes(col = Outcome)) +
  geom_hline(aes(fill = Outcome), yintercept = 0, linetype = 2) +
  xlab("") +
  ylab("Effect sizes (95% Confidence Interval)") +
  geom_errorbar(aes(ymin = low, ymax = hi, col = Outcome), width = 0.5, cex = 1) +
  scale_color_npg() +
  guides(color = guide_legend(reverse=TRUE)) + 
  facet_grid(Predictor~type, labeller = labeller(Predictor = label_parsed)) +
  #scale_y_continuous(limits = c(-1, 6), breaks = c(-1, 0, 1, 2, 3, 4, 5, 6)) +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.x = element_text(face = "bold"),
    axis.title = element_text(size = 12, face = "bold"),
    strip.text.y = element_text(angle = 0, face = "bold")
  ) +
  coord_flip() +
  ggtitle("")

p
```

### Z-score based AL score
```{r}
ap_hsr_outzps <- ap_hsr_outzps %>%
  dplyr::rename(
    "beta" = "beta_mod4",
    "low" = "cilo_mod4",
    "hi" = "cihi_mod4"
  ) %>% 
  mutate(type = if_else(str_detect(Predictor, "_h$"), "Home", 
                        if_else(str_detect(Predictor, "_s$"), "School", "Commuting"))) %>% 
  mutate_at("Predictor", as_factor) %>%
  mutate(Predictor = recode(Predictor,
    "hs_no2_yr_hs_h" = "NO[2]",
    "hs_no2_yr_hs_s" = "NO[2]",
    "hs_no2_yr_hs_r" = "NO[2]",
    "hs_pm10_yr_hs_h" = "PM[10]",
    "hs_pm10_yr_hs_s" = "PM[10]",
    "hs_pm10_yr_hs_r" = "PM[10]",
    "hs_pm25_yr_hs_h" = "PM[2.5]",
    "hs_pm25_yr_hs_s" = "PM[2.5]",
    "hs_pm25_yr_hs_r" = "PM[2.5]",
    "hs_pm25abs_yr_hs_h" = "PM[2.5][abs]",
    "hs_pm25abs_yr_hs_s" = "PM[2.5][abs]",
    "hs_pm25abs_yr_hs_r" = "PM[2.5][abs]"
  )) 
```

```{r fig.asp = 1, fig.width=10}
p <- ggplot(
  data = ap_hsr_outzps,
  aes(x = Outcome, y = beta, ymin = low, ymax = hi)
) +
  geom_pointrange(aes(col = Outcome)) +
  geom_hline(aes(fill = Outcome), yintercept = 0, linetype = 2) +
  xlab("") +
  ylab("Effect sizes (95% Confidence Interval)") +
  geom_errorbar(aes(ymin = low, ymax = hi, col = Outcome), width = 0.5, cex = 1) +
  scale_color_npg() +
  guides(color = guide_legend(reverse=TRUE)) + 
  facet_grid(Predictor~type, labeller = labeller(Predictor = label_parsed)) +
  #scale_y_continuous(limits = c(-1, 6), breaks = c(-1, 0, 1, 2, 3, 4, 5, 6)) +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.x = element_text(face = "bold"),
    axis.title = element_text(size = 12, face = "bold"),
    strip.text.y = element_text(angle = 0, face = "bold")
  ) +
  coord_flip() +
  ggtitle("")

p
```
